// ============================================
// SHARED DATA SOURCE - All 12 Products
// ============================================

window.products = [
    {
        id: 1,
        name: "Madhubani Painting",
        category: "paintings",
        region: "Bihar",
        price: 2500,
        originalPrice: 3125,
        discount: 20,
        rating: 4.9,
        reviews: 128,
        icon: "ph-paint-brush",
        image: "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1582738411706-bfc8e691d1c2?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An exquisite Madhubani painting showcasing the traditional folk art of Bihar. Hand-painted with intricate patterns and vibrant natural colors.",
        materials: "Natural dyes, Handmade paper, Rice paste",
        dimensions: "30cm x 40cm",
        weight: "200g",
        artForm: "Madhubani Folk Art",
        deliveryTime: "5-7 business days",
        detailedDescription: "This stunning Madhubani painting is a testament to the rich artistic heritage of Bihar. Created using traditional techniques preserved for centuries, featuring characteristic double-line borders and vibrant natural colors derived from plants and minerals.",
        craftStory: "Madhubani art originated in the Mithila region of Bihar over 2500 years ago. Traditionally practiced by women on mud walls during festivals, it has evolved to canvas and paper while preserving traditional techniques.",
        careInstructions: ["Frame under glass", "Keep away from sunlight", "Avoid high humidity", "Clean glass gently"],
        artisan: {
            name: "Sita Devi",
            avatar: "ph-user-circle",
            location: "Madhubani, Bihar",
            experience: "25+ years",
            products: 85,
            rating: 4.9,
            sales: 650,
            bio: "Master Madhubani artist who learned from her mother and grandmother. Her work has been exhibited in galleries across India.",
            specialization: "Madhubani Folk Painting"
        }
    },
    {
        id: 2,
        name: "Terracotta Vase",
        category: "pottery",
        region: "West Bengal",
        price: 1200,
        originalPrice: 1500,
        discount: 20,
        rating: 4.8,
        reviews: 89,
        icon: "ph-vase",
        image: "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1565193566173-7a0ee3dbe261?w=600&auto=format&fit=crop&q=80"
        ],
        description: "A beautifully handcrafted terracotta vase from West Bengal's renowned pottery workshops. Traditional earthenware with excellent craftsmanship.",
        materials: "Natural terracotta clay, Eco-friendly glazing",
        dimensions: "Height: 25cm, Diameter: 15cm",
        weight: "800g",
        artForm: "Traditional Terracotta Pottery",
        deliveryTime: "5-7 business days",
        detailedDescription: "This stunning terracotta vase represents the finest tradition of West Bengal pottery, shaped on a traditional potter's wheel and fired in a kiln.",
        craftStory: "Terracotta pottery in West Bengal has a history spanning thousands of years, central to Bengali culture and daily life.",
        careInstructions: ["Rinse before first use", "Hand wash gently", "Avoid thermal shock", "Handle with care"],
        artisan: {
            name: "Ranjan Pal",
            avatar: "ph-user-circle",
            location: "Kumartuli, West Bengal",
            experience: "30+ years",
            products: 120,
            rating: 4.8,
            sales: 890,
            bio: "From a family of traditional potters in Kumartuli, Kolkata's famous pottery district.",
            specialization: "Terracotta Pottery"
        }
    },
    {
        id: 3,
        name: "Bandhani Saree",
        category: "textiles",
        region: "Gujarat",
        price: 3500,
        originalPrice: 4375,
        discount: 20,
        rating: 4.9,
        reviews: 210,
        icon: "ph-scroll",
        image: "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1610030469983-98e550d6193c?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An authentic Bandhani saree featuring the traditional tie-dye technique of Gujarat with thousands of tiny knots creating stunning patterns.",
        materials: "Pure cotton, Natural dyes, Traditional tie-dye",
        dimensions: "Length: 6.5 meters (with blouse piece)",
        weight: "450g",
        artForm: "Bandhani Tie-Dye",
        deliveryTime: "7-10 business days",
        detailedDescription: "This exquisite Bandhani saree is a masterpiece of traditional Gujarati craftsmanship, each featuring thousands of tiny dots.",
        craftStory: "Bandhani is an ancient tie-dye art practiced in Gujarat for over 5000 years, traditionally worn by royalty.",
        careInstructions: ["Dry clean recommended", "Use cold water if hand washing", "Wash separately", "Dry in shade"],
        artisan: {
            name: "Lakshmi Ben Patel",
            avatar: "ph-user-circle",
            location: "Bhuj, Gujarat",
            experience: "20+ years",
            products: 95,
            rating: 4.9,
            sales: 420,
            bio: "Renowned Bandhani artist from Bhuj, preserving authentic traditions.",
            specialization: "Bandhani Tie-Dye"
        }
    },
    {
        id: 4,
        name: "Silver Anklet",
        category: "jewelry",
        region: "Rajasthan",
        price: 1800,
        originalPrice: 2250,
        discount: 20,
        rating: 4.7,
        reviews: 76,
        icon: "ph-diamond",
        image: "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1515562141207-7a88fb7ce338?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An elegant sterling silver anklet handcrafted by skilled artisans of Rajasthan with intricate designs and delicate bells.",
        materials: "92.5% Sterling Silver",
        dimensions: "Length: 25cm (adjustable)",
        weight: "35g",
        artForm: "Traditional Silver Jewelry",
        deliveryTime: "5-7 business days",
        detailedDescription: "This beautiful silver anklet features intricate patterns and small bells that create a gentle chiming sound.",
        craftStory: "Silver jewelry making in Rajasthan dates back centuries, with artisans using traditional techniques.",
        careInstructions: ["Clean with soft cloth", "Store in airtight container", "Avoid perfumes", "Polish occasionally"],
        artisan: {
            name: "Mohan Lal Solanki",
            avatar: "ph-user-circle",
            location: "Jaipur, Rajasthan",
            experience: "35+ years",
            products: 150,
            rating: 4.9,
            sales: 780,
            bio: "Master silversmith from Jaipur with 35 years of experience.",
            specialization: "Sterling Silver Jewelry"
        }
    },
    {
        id: 5,
        name: "Warli Art Frame",
        category: "paintings",
        region: "Maharashtra",
        price: 1500,
        originalPrice: 1875,
        discount: 20,
        rating: 4.6,
        reviews: 45,
        icon: "ph-frame-corners",
        image: "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1578301978693-85fa9c0320b9?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An authentic Warli art painting showcasing the tribal art form of Maharashtra with simple geometric shapes depicting daily life.",
        materials: "Natural pigments, Canvas",
        dimensions: "25cm x 35cm (framed)",
        weight: "350g",
        artForm: "Warli Tribal Art",
        deliveryTime: "5-7 business days",
        detailedDescription: "This captivating Warli painting brings to life the ancient tribal art using white pigment on contrasting background.",
        craftStory: "Warli painting is one of India's oldest art forms, dating back to 2500-3000 BCE.",
        careInstructions: ["Keep away from sunlight", "Hang in moderate humidity", "Clean frame glass only"],
        artisan: {
            name: "Jivya Soma Mashe Jr.",
            avatar: "ph-user-circle",
            location: "Ganjad Village, Maharashtra",
            experience: "18+ years",
            products: 110,
            rating: 4.8,
            sales: 520,
            bio: "Renowned Warli artist following his legendary father's footsteps.",
            specialization: "Warli Tribal Art"
        }
    },
    {
        id: 6,
        name: "Brass Diya Set",
        category: "handicrafts",
        region: "Tamil Nadu",
        price: 800,
        originalPrice: 1000,
        discount: 20,
        rating: 4.8,
        reviews: 156,
        icon: "ph-fire",
        image: "https://images.unsplash.com/photo-1605290477633-24ebf559e5b3?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1605290477633-24ebf559e5b3?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1605290477633-24ebf559e5b3?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1605290477633-24ebf559e5b3?w=600&auto=format&fit=crop&q=80"
        ],
        description: "A beautiful set of handcrafted brass diyas from Tamil Nadu, perfect for festivals and home decoration.",
        materials: "Pure brass, Traditional hand-forging",
        dimensions: "Each diya: 8cm diameter, Set of 5",
        weight: "600g (complete set)",
        artForm: "Traditional Brass Craft",
        deliveryTime: "5-7 business days",
        detailedDescription: "This exquisite set of five brass diyas represents the finest tradition of South Indian metal craft.",
        craftStory: "Brass craftsmanship in Tamil Nadu has a rich history spanning over a thousand years.",
        careInstructions: ["Clean with lemon to restore shine", "Dry thoroughly", "Store in dry place"],
        artisan: {
            name: "Venkatesh Iyer",
            avatar: "ph-user-circle",
            location: "Kumbakonam, Tamil Nadu",
            experience: "28+ years",
            products: 200,
            rating: 4.7,
            sales: 950,
            bio: "Master brass craftsman from Kumbakonam.",
            specialization: "Brass Craftsmanship"
        }
    },
    {
        id: 7,
        name: "Blue Pottery Bowl",
        category: "pottery",
        region: "Rajasthan",
        price: 950,
        originalPrice: 1188,
        discount: 20,
        rating: 4.8,
        reviews: 92,
        icon: "ph-bowl-food",
        image: "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1610701596007-11502861dcfa?w=600&auto=format&fit=crop&q=80"
        ],
        description: "A stunning Jaipur blue pottery bowl featuring characteristic turquoise blue glaze and intricate floral patterns.",
        materials: "Quartz stone powder, Multani mitti, Natural dyes",
        dimensions: "Diameter: 20cm, Height: 8cm",
        weight: "400g",
        artForm: "Jaipur Blue Pottery",
        deliveryTime: "5-7 business days",
        detailedDescription: "This exquisite blue pottery bowl showcases the unique art form that made Jaipur famous worldwide.",
        craftStory: "Blue pottery traces its origins to Turko-Persian heritage, brought to Jaipur in the 14th century.",
        careInstructions: ["Hand wash gently", "Not microwave safe", "Avoid temperature changes", "Dry immediately"],
        artisan: {
            name: "Kripal Singh Shekhawat",
            avatar: "ph-user-circle",
            location: "Jaipur, Rajasthan",
            experience: "22+ years",
            products: 180,
            rating: 4.8,
            sales: 640,
            bio: "Learned blue pottery from his legendary grandfather.",
            specialization: "Jaipur Blue Pottery"
        }
    },
    {
        id: 8,
        name: "Pattachitra Scroll",
        category: "paintings",
        region: "Odisha",
        price: 3200,
        originalPrice: 4000,
        discount: 20,
        rating: 4.9,
        reviews: 67,
        icon: "ph-scroll",
        image: "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1579783902614-a3fb3927b6a5?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An authentic Pattachitra scroll painting depicting mythological narratives in traditional Odisha style with natural colors.",
        materials: "Treated cloth canvas, Natural mineral colors",
        dimensions: "45cm x 60cm",
        weight: "300g",
        artForm: "Pattachitra Scroll Painting",
        deliveryTime: "7-10 business days",
        detailedDescription: "This magnificent Pattachitra painting is a masterpiece of one of India's oldest art forms.",
        craftStory: "Pattachitra, meaning 'cloth picture', dates back to the 5th century BCE, originally for temple walls.",
        careInstructions: ["Frame under glass", "Keep away from sunlight", "Avoid humidity", "Don't fold"],
        artisan: {
            name: "Raghunath Mahapatra",
            avatar: "ph-user-circle",
            location: "Raghurajpur, Odisha",
            experience: "32+ years",
            products: 95,
            rating: 4.9,
            sales: 380,
            bio: "National Award-winning Pattachitra artist from heritage crafts village.",
            specialization: "Pattachitra Scroll Painting"
        }
    },
    {
        id: 9,
        name: "Kashmiri Pashmina",
        category: "textiles",
        region: "Jammu & Kashmir",
        price: 5500,
        originalPrice: 6875,
        discount: 20,
        rating: 5.0,
        reviews: 145,
        icon: "ph-coat-hanger",
        image: "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1601924994987-69e26d50dc26?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An authentic Kashmiri Pashmina shawl hand-woven from the finest cashmere wool with traditional embroidery.",
        materials: "100% Pure Pashmina (Cashmere)",
        dimensions: "200cm x 100cm",
        weight: "180g",
        artForm: "Kashmiri Pashmina Weaving",
        deliveryTime: "7-10 business days",
        detailedDescription: "This exquisite Pashmina shawl represents the pinnacle of Kashmiri craftsmanship, incredibly soft and warm.",
        craftStory: "Pashmina weaving in Kashmir dates back over 500 years, prized by royalty worldwide.",
        careInstructions: ["Dry clean only", "Store folded", "Use mothballs", "Iron on low heat"],
        artisan: {
            name: "Abdul Rashid",
            avatar: "ph-user-circle",
            location: "Srinagar, Kashmir",
            experience: "40+ years",
            products: 65,
            rating: 5.0,
            sales: 290,
            bio: "Master weaver from a family creating Pashmina for four generations.",
            specialization: "Pashmina Hand-Weaving"
        }
    },
    {
        id: 10,
        name: "Temple Jewelry Set",
        category: "jewelry",
        region: "Tamil Nadu",
        price: 2200,
        originalPrice: 2750,
        discount: 20,
        rating: 4.8,
        reviews: 118,
        icon: "ph-diamond",
        image: "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1535632066927-ab7c9ab60908?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An elegant temple jewelry set featuring traditional South Indian designs with gold-plated finish.",
        materials: "Brass base, 22K gold plating, Semi-precious stones",
        dimensions: "Necklace: 40cm, Earrings: 6cm",
        weight: "150g (complete set)",
        artForm: "Temple Jewelry Crafting",
        deliveryTime: "5-7 business days",
        detailedDescription: "This stunning temple jewelry set is inspired by ornaments adorning deities in ancient temples.",
        craftStory: "Temple jewelry has origins in South Indian temples, dating back to the Chola dynasty.",
        careInstructions: ["Store in jewelry box", "Avoid chemicals", "Clean with soft cloth", "Remove before bathing"],
        artisan: {
            name: "Meenakshi Sundaram",
            avatar: "ph-user-circle",
            location: "Kumbakonam, Tamil Nadu",
            experience: "26+ years",
            products: 140,
            rating: 4.8,
            sales: 560,
            bio: "Master craftsman specializing in traditional temple jewelry.",
            specialization: "Temple Jewelry"
        }
    },
    {
        id: 11,
        name: "Bamboo Basket",
        category: "handicrafts",
        region: "Assam",
        price: 600,
        originalPrice: 750,
        discount: 20,
        rating: 4.7,
        reviews: 83,
        icon: "ph-basket",
        image: "https://images.unsplash.com/photo-1595408076683-5d0c839a0a69?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1595408076683-5d0c839a0a69?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1595408076683-5d0c839a0a69?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1595408076683-5d0c839a0a69?w=600&auto=format&fit=crop&q=80"
        ],
        description: "A beautifully handwoven bamboo basket from Assam, showcasing traditional weaving techniques. Eco-friendly and durable.",
        materials: "100% Natural bamboo",
        dimensions: "Diameter: 35cm, Height: 20cm",
        weight: "400g",
        artForm: "Traditional Bamboo Craft",
        deliveryTime: "5-7 business days",
        detailedDescription: "This exquisite bamboo basket represents the rich tradition of Assamese bamboo craftsmanship.",
        craftStory: "Bamboo craft is integral to Assamese culture, practiced for thousands of years.",
        careInstructions: ["Clean with damp cloth", "Avoid prolonged water exposure", "Keep ventilated", "Apply oil occasionally"],
        artisan: {
            name: "Biren Gogoi",
            avatar: "ph-user-circle",
            location: "Jorhat, Assam",
            experience: "24+ years",
            products: 220,
            rating: 4.7,
            sales: 890,
            bio: "Skilled bamboo craftsman dedicated to sustainable craftsmanship.",
            specialization: "Bamboo Weaving"
        }
    },
    {
        id: 12,
        name: "Dhokra Horse",
        category: "handicrafts",
        region: "Chhattisgarh",
        price: 1400,
        originalPrice: 1750,
        discount: 20,
        rating: 4.9,
        reviews: 72,
        icon: "ph-horse",
        image: "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80",
        images: [
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80",
            "https://images.unsplash.com/photo-1558618666-fcd25c85cd64?w=600&auto=format&fit=crop&q=80"
        ],
        description: "An authentic Dhokra horse figurine crafted using the ancient lost-wax casting technique from Chhattisgarh.",
        materials: "Brass and copper alloy",
        dimensions: "Height: 15cm, Length: 18cm",
        weight: "650g",
        artForm: "Dhokra Metal Casting",
        deliveryTime: "5-7 business days",
        detailedDescription: "This remarkable Dhokra horse is a stunning example of India's oldest metal casting tradition, over 4,000 years old.",
        craftStory: "Dhokra is a 4,000-year-old craft using the same technique as the Dancing Girl of Mohenjo-Daro.",
        careInstructions: ["Dust regularly", "Apply thin oil coat", "Keep away from moisture", "Polish gently if needed"],
        artisan: {
            name: "Sukra Manjhi",
            avatar: "ph-user-circle",
            location: "Kondagaon, Chhattisgarh",
            experience: "30+ years",
            products: 175,
            rating: 4.9,
            sales: 430,
            bio: "From the Ghadwa tribal community, mastered the ancient lost-wax technique.",
            specialization: "Dhokra Lost-Wax Casting"
        }
    }
];
